# vim: ft=ruby

http_file(
  name: "dist",
  url: "https://download.java.net/java/GA/jdk15/779bf45e88a44cbd9ea6621d33e33db1/36/GPL/openjdk-15_osx-x64_bin.tar.gz",
  sha256: "ab842c8c0953b816be308c098c1a021177a4776bef24da85b6bafbbd657c7e1a",
  os: :macos,
)

# tar tzf openjdk-15_osx-x64_bin.tar.gz | grep -v '/$' | grep -v '/legal/' | cut -d/ -f4- | sort | pbcopy
#
# CodeResources
# Home/bin/jaotc
# Home/bin/jar
# Home/bin/jarsigner
# Home/bin/java
# Home/bin/javac
# Home/bin/javadoc
# Home/bin/javap
# Home/bin/jcmd
# Home/bin/jconsole
# Home/bin/jdb
# Home/bin/jdeprscan
# Home/bin/jdeps
# Home/bin/jfr
# Home/bin/jhsdb
# Home/bin/jimage
# Home/bin/jinfo
# Home/bin/jlink
# Home/bin/jmap
# Home/bin/jmod
# Home/bin/jpackage
# Home/bin/jps
# Home/bin/jrunscript
# Home/bin/jshell
# Home/bin/jstack
# Home/bin/jstat
# Home/bin/jstatd
# Home/bin/keytool
# Home/bin/rmid
# Home/bin/rmiregistry
# Home/bin/serialver
# Home/conf/logging.properties
# Home/conf/management/jmxremote.access
# Home/conf/management/jmxremote.password.template
# Home/conf/management/management.properties
# Home/conf/net.properties
# Home/conf/security/java.policy
# Home/conf/security/java.security
# Home/conf/security/policy/README.txt
# Home/conf/security/policy/limited/default_US_export.policy
# Home/conf/security/policy/limited/default_local.policy
# Home/conf/security/policy/limited/exempt_local.policy
# Home/conf/security/policy/unlimited/default_US_export.policy
# Home/conf/security/policy/unlimited/default_local.policy
# Home/conf/sound.properties
# Home/include/classfile_constants.h
# Home/include/darwin/jawt_md.h
# Home/include/darwin/jni_md.h
# Home/include/jawt.h
# Home/include/jdwpTransport.h
# Home/include/jni.h
# Home/include/jvmti.h
# Home/include/jvmticmlr.h
# Home/jmods/java.base.jmod
# Home/jmods/java.compiler.jmod
# Home/jmods/java.datatransfer.jmod
# Home/jmods/java.desktop.jmod
# Home/jmods/java.instrument.jmod
# Home/jmods/java.logging.jmod
# Home/jmods/java.management.jmod
# Home/jmods/java.management.rmi.jmod
# Home/jmods/java.naming.jmod
# Home/jmods/java.net.http.jmod
# Home/jmods/java.prefs.jmod
# Home/jmods/java.rmi.jmod
# Home/jmods/java.scripting.jmod
# Home/jmods/java.se.jmod
# Home/jmods/java.security.jgss.jmod
# Home/jmods/java.security.sasl.jmod
# Home/jmods/java.smartcardio.jmod
# Home/jmods/java.sql.jmod
# Home/jmods/java.sql.rowset.jmod
# Home/jmods/java.transaction.xa.jmod
# Home/jmods/java.xml.crypto.jmod
# Home/jmods/java.xml.jmod
# Home/jmods/jdk.accessibility.jmod
# Home/jmods/jdk.aot.jmod
# Home/jmods/jdk.attach.jmod
# Home/jmods/jdk.charsets.jmod
# Home/jmods/jdk.compiler.jmod
# Home/jmods/jdk.crypto.cryptoki.jmod
# Home/jmods/jdk.crypto.ec.jmod
# Home/jmods/jdk.dynalink.jmod
# Home/jmods/jdk.editpad.jmod
# Home/jmods/jdk.hotspot.agent.jmod
# Home/jmods/jdk.httpserver.jmod
# Home/jmods/jdk.incubator.foreign.jmod
# Home/jmods/jdk.incubator.jpackage.jmod
# Home/jmods/jdk.internal.ed.jmod
# Home/jmods/jdk.internal.jvmstat.jmod
# Home/jmods/jdk.internal.le.jmod
# Home/jmods/jdk.internal.opt.jmod
# Home/jmods/jdk.internal.vm.ci.jmod
# Home/jmods/jdk.internal.vm.compiler.jmod
# Home/jmods/jdk.internal.vm.compiler.management.jmod
# Home/jmods/jdk.jartool.jmod
# Home/jmods/jdk.javadoc.jmod
# Home/jmods/jdk.jcmd.jmod
# Home/jmods/jdk.jconsole.jmod
# Home/jmods/jdk.jdeps.jmod
# Home/jmods/jdk.jdi.jmod
# Home/jmods/jdk.jdwp.agent.jmod
# Home/jmods/jdk.jfr.jmod
# Home/jmods/jdk.jlink.jmod
# Home/jmods/jdk.jshell.jmod
# Home/jmods/jdk.jsobject.jmod
# Home/jmods/jdk.jstatd.jmod
# Home/jmods/jdk.localedata.jmod
# Home/jmods/jdk.management.agent.jmod
# Home/jmods/jdk.management.jfr.jmod
# Home/jmods/jdk.management.jmod
# Home/jmods/jdk.naming.dns.jmod
# Home/jmods/jdk.naming.rmi.jmod
# Home/jmods/jdk.net.jmod
# Home/jmods/jdk.nio.mapmode.jmod
# Home/jmods/jdk.sctp.jmod
# Home/jmods/jdk.security.auth.jmod
# Home/jmods/jdk.security.jgss.jmod
# Home/jmods/jdk.unsupported.desktop.jmod
# Home/jmods/jdk.unsupported.jmod
# Home/jmods/jdk.xml.dom.jmod
# Home/jmods/jdk.zipfs.jmod
# Home/lib/classlist
# Home/lib/ct.sym
# Home/lib/fontconfig.bfc
# Home/lib/fontconfig.properties.src
# Home/lib/jfr/default.jfc
# Home/lib/jfr/profile.jfc
# Home/lib/jrt-fs.jar
# Home/lib/jspawnhelper
# Home/lib/jvm.cfg
# Home/lib/libattach.dylib
# Home/lib/libawt.dylib
# Home/lib/libawt_lwawt.dylib
# Home/lib/libdt_socket.dylib
# Home/lib/libextnet.dylib
# Home/lib/libfontmanager.dylib
# Home/lib/libfreetype.dylib
# Home/lib/libinstrument.dylib
# Home/lib/libj2gss.dylib
# Home/lib/libj2pcsc.dylib
# Home/lib/libj2pkcs11.dylib
# Home/lib/libjaas.dylib
# Home/lib/libjava.dylib
# Home/lib/libjavajpeg.dylib
# Home/lib/libjawt.dylib
# Home/lib/libjdwp.dylib
# Home/lib/libjimage.dylib
# Home/lib/libjli.dylib
# Home/lib/libjsig.dylib
# Home/lib/libjsound.dylib
# Home/lib/liblcms.dylib
# Home/lib/libmanagement.dylib
# Home/lib/libmanagement_agent.dylib
# Home/lib/libmanagement_ext.dylib
# Home/lib/libmlib_image.dylib
# Home/lib/libnet.dylib
# Home/lib/libnio.dylib
# Home/lib/libosx.dylib
# Home/lib/libosxapp.dylib
# Home/lib/libosxkrb5.dylib
# Home/lib/libosxsecurity.dylib
# Home/lib/libosxui.dylib
# Home/lib/libprefs.dylib
# Home/lib/librmi.dylib
# Home/lib/libsaproc.dylib
# Home/lib/libsplashscreen.dylib
# Home/lib/libsunec.dylib
# Home/lib/libverify.dylib
# Home/lib/libzip.dylib
# Home/lib/modules
# Home/lib/psfont.properties.ja
# Home/lib/psfontj2d.properties
# Home/lib/security/blacklisted.certs
# Home/lib/security/cacerts
# Home/lib/security/default.policy
# Home/lib/security/public_suffix_list.dat
# Home/lib/server/classes.jsa
# Home/lib/server/classes_nocoops.jsa
# Home/lib/server/libjsig.dylib
# Home/lib/server/libjvm.dylib
# Home/lib/src.zip
# Home/lib/tzdb.dat
# Home/release
# Info.plist
# MacOS/libjli.dylib
# _CodeSignature/CodeResources

extract(
  name: "bin_jar",
  archive: ":dist",
  format: :tar_gz,
  paths: ["bin/jar"],
  strip_components: 3,
  os: :macos,
)

extract(
  name: "bin_java",
  archive: ":dist",
  format: :tar_gz,
  paths: ["bin/java"],
  strip_components: 3,
  os: :macos,
)

extract(
  name: "bin_jdb",
  archive: ":dist",
  format: :tar_gz,
  paths: ["bin/jdb"],
  strip_components: 3,
  os: :macos,
)

extract(
  name: "lib",
  archive: ":dist",
  format: :tar_gz,
  paths: [
    "conf/logging.properties",
    "conf/management/jmxremote.access",
    "conf/management/jmxremote.password.template",
    "conf/management/management.properties",
    "conf/net.properties",
    "conf/security/java.policy",
    "conf/security/java.security",
    "conf/security/policy/limited/default_US_export.policy",
    "conf/security/policy/limited/default_local.policy",
    "conf/security/policy/limited/exempt_local.policy",
    "conf/security/policy/unlimited/default_US_export.policy",
    "conf/security/policy/unlimited/default_local.policy",
    "conf/sound.properties",
    "lib/classlist",
    "lib/ct.sym",
    "lib/fontconfig.bfc",
    "lib/fontconfig.properties.src",
    "lib/jfr/default.jfc",
    "lib/jfr/profile.jfc",
    "lib/jrt-fs.jar",
    "lib/jspawnhelper",
    "lib/jvm.cfg",
    "lib/libattach.dylib",
    "lib/libawt.dylib",
    "lib/libawt_lwawt.dylib",
    "lib/libdt_socket.dylib",
    "lib/libextnet.dylib",
    "lib/libfontmanager.dylib",
    "lib/libfreetype.dylib",
    "lib/libinstrument.dylib",
    "lib/libj2gss.dylib",
    "lib/libj2pcsc.dylib",
    "lib/libj2pkcs11.dylib",
    "lib/libjaas.dylib",
    "lib/libjava.dylib",
    "lib/libjavajpeg.dylib",
    "lib/libjawt.dylib",
    "lib/libjdwp.dylib",
    "lib/libjimage.dylib",
    "lib/libjli.dylib",
    "lib/libjsig.dylib",
    "lib/libjsound.dylib",
    "lib/liblcms.dylib",
    "lib/libmanagement.dylib",
    "lib/libmanagement_agent.dylib",
    "lib/libmanagement_ext.dylib",
    "lib/libmlib_image.dylib",
    "lib/libnet.dylib",
    "lib/libnio.dylib",
    "lib/libosx.dylib",
    "lib/libosxapp.dylib",
    "lib/libosxkrb5.dylib",
    "lib/libosxsecurity.dylib",
    "lib/libosxui.dylib",
    "lib/libprefs.dylib",
    "lib/librmi.dylib",
    "lib/libsaproc.dylib",
    "lib/libsplashscreen.dylib",
    "lib/libsunec.dylib",
    "lib/libverify.dylib",
    "lib/libzip.dylib",
    "lib/modules",
    "lib/psfont.properties.ja",
    "lib/psfontj2d.properties",
    "lib/security/blacklisted.certs",
    "lib/security/cacerts",
    "lib/security/default.policy",
    "lib/security/public_suffix_list.dat",
    "lib/server/classes.jsa",
    "lib/server/libjsig.dylib",
    "lib/server/libjvm.dylib",
    "lib/src.zip",
    "lib/tzdb.dat",
  ],
  strip_components: 3,
  os: :macos,
)

java_archiver(
  name: "archiver",
  jar: ":bin_jar",
  libs: ":lib",
  os: :macos,
)

java_runtime(
  name: "runtime",
  java: ":bin_java",
  libs: ":lib",
  os: :macos,
)
