java_library(
    name = "console",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/main/java/org/matthewtodd/perquackey/console:__pkg__",
        "//src/test/java/org/matthewtodd/console:__pkg__",
        "//src/test/java/org/matthewtodd/perquackey/console:__pkg__",
    ],
    deps = [
        "//src/main/java/org/matthewtodd/flow",
        "@org_jline_jline_terminal",
    ],
)
