java_library(
    name = "bazel",
    srcs = glob(["**/*.java"]),
    resources = glob(["META-INF/*"]),
    resource_strip_prefix = "src/main/java/org/matthewtodd/intellij/bazel",
    deps = [
        "@intellij//:sdk",
    ],
)
