# vim: ft=ruby

http_file(
  name: "dist",
  url: "https://download.java.net/java/GA/jdk13.0.2/d4173c853231432d94f001e99d882ca7/8/GPL/openjdk-13.0.2_osx-x64_bin.tar.gz",
  sha256: "08fd2db3a3ab6fb82bb9091a035f9ffe8ae56c31725f4e17d573e48c39ca10dd",
)

# bin/jaotc
# bin/jar
# bin/jarsigner
# bin/java
# bin/javac
# bin/javadoc
# bin/javap
# bin/jcmd
# bin/jconsole
# bin/jdb
# bin/jdeprscan
# bin/jdeps
# bin/jfr
# bin/jhsdb
# bin/jimage
# bin/jinfo
# bin/jjs
# bin/jlink
# bin/jmap
# bin/jmod
# bin/jps
# bin/jrunscript
# bin/jshell
# bin/jstack
# bin/jstat
# bin/jstatd
# bin/keytool
# bin/pack200
# bin/rmic
# bin/rmid
# bin/rmiregistry
# bin/serialver
# bin/unpack200
# jmods/java.base.jmod
# jmods/java.compiler.jmod
# jmods/java.datatransfer.jmod
# jmods/java.desktop.jmod
# jmods/java.instrument.jmod
# jmods/java.logging.jmod
# jmods/java.management.jmod
# jmods/java.management.rmi.jmod
# jmods/java.naming.jmod
# jmods/java.net.http.jmod
# jmods/java.prefs.jmod
# jmods/java.rmi.jmod
# jmods/java.scripting.jmod
# jmods/java.se.jmod
# jmods/java.security.jgss.jmod
# jmods/java.security.sasl.jmod
# jmods/java.smartcardio.jmod
# jmods/java.sql.jmod
# jmods/java.sql.rowset.jmod
# jmods/java.transaction.xa.jmod
# jmods/java.xml.crypto.jmod
# jmods/java.xml.jmod
# jmods/jdk.accessibility.jmod
# jmods/jdk.aot.jmod
# jmods/jdk.attach.jmod
# jmods/jdk.charsets.jmod
# jmods/jdk.compiler.jmod
# jmods/jdk.crypto.cryptoki.jmod
# jmods/jdk.crypto.ec.jmod
# jmods/jdk.dynalink.jmod
# jmods/jdk.editpad.jmod
# jmods/jdk.hotspot.agent.jmod
# jmods/jdk.httpserver.jmod
# jmods/jdk.internal.ed.jmod
# jmods/jdk.internal.jvmstat.jmod
# jmods/jdk.internal.le.jmod
# jmods/jdk.internal.opt.jmod
# jmods/jdk.internal.vm.ci.jmod
# jmods/jdk.internal.vm.compiler.jmod
# jmods/jdk.internal.vm.compiler.management.jmod
# jmods/jdk.jartool.jmod
# jmods/jdk.javadoc.jmod
# jmods/jdk.jcmd.jmod
# jmods/jdk.jconsole.jmod
# jmods/jdk.jdeps.jmod
# jmods/jdk.jdi.jmod
# jmods/jdk.jdwp.agent.jmod
# jmods/jdk.jfr.jmod
# jmods/jdk.jlink.jmod
# jmods/jdk.jshell.jmod
# jmods/jdk.jsobject.jmod
# jmods/jdk.jstatd.jmod
# jmods/jdk.localedata.jmod
# jmods/jdk.management.agent.jmod
# jmods/jdk.management.jfr.jmod
# jmods/jdk.management.jmod
# jmods/jdk.naming.dns.jmod
# jmods/jdk.naming.rmi.jmod
# jmods/jdk.net.jmod
# jmods/jdk.pack.jmod
# jmods/jdk.rmic.jmod
# jmods/jdk.scripting.nashorn.jmod
# jmods/jdk.scripting.nashorn.shell.jmod
# jmods/jdk.sctp.jmod
# jmods/jdk.security.auth.jmod
# jmods/jdk.security.jgss.jmod
# jmods/jdk.unsupported.desktop.jmod
# jmods/jdk.unsupported.jmod
# jmods/jdk.xml.dom.jmod
# jmods/jdk.zipfs.jmod
# lib/classlist
# lib/ct.sym
# lib/fontconfig.bfc
# lib/fontconfig.properties.src
# lib/jfr/default.jfc
# lib/jfr/profile.jfc
# lib/jrt-fs.jar
# lib/jspawnhelper
# lib/jvm.cfg
# lib/libattach.dylib
# lib/libawt.dylib
# lib/libawt_lwawt.dylib
# lib/libdt_socket.dylib
# lib/libextnet.dylib
# lib/libfontmanager.dylib
# lib/libfreetype.dylib
# lib/libinstrument.dylib
# lib/libj2gss.dylib
# lib/libj2pcsc.dylib
# lib/libj2pkcs11.dylib
# lib/libjaas.dylib
# lib/libjava.dylib
# lib/libjavajpeg.dylib
# lib/libjawt.dylib
# lib/libjdwp.dylib
# lib/libjimage.dylib
# lib/libjli.dylib
# lib/libjsig.dylib
# lib/libjsound.dylib
# lib/liblcms.dylib
# lib/libmanagement.dylib
# lib/libmanagement_agent.dylib
# lib/libmanagement_ext.dylib
# lib/libmlib_image.dylib
# lib/libnet.dylib
# lib/libnio.dylib
# lib/libosx.dylib
# lib/libosxapp.dylib
# lib/libosxkrb5.dylib
# lib/libosxsecurity.dylib
# lib/libosxui.dylib
# lib/libprefs.dylib
# lib/librmi.dylib
# lib/libsaproc.dylib
# lib/libsplashscreen.dylib
# lib/libsunec.dylib
# lib/libunpack.dylib
# lib/libverify.dylib
# lib/libzip.dylib
# lib/modules
# lib/psfont.properties.ja
# lib/psfontj2d.properties
# lib/security/blacklisted.certs
# lib/security/cacerts
# lib/security/default.policy
# lib/security/public_suffix_list.dat
# lib/server/classes.jsa
# lib/server/libjsig.dylib
# lib/server/libjvm.dylib
# lib/src.zip
# lib/tzdb.dat

extract(
  name: "bin_javac",
  archive: "//lib/java/jdk13_macos:dist",
  format: :tar_gz,
  paths: ["bin/javac"],
  permissions: 0755,
  strip_components: 3,
)

extract(
  name: "bin_jar",
  archive: "//lib/java/jdk13_macos:dist",
  format: :tar_gz,
  paths: ["bin/jar"],
  permissions: 0755,
  strip_components: 3,
)

extract(
  name: "bin_javac_libs",
  archive: "//lib/java/jdk13_macos:dist",
  format: :tar_gz,
  paths: [
    "lib/classlist",
    "lib/ct.sym",
    "lib/fontconfig.bfc",
    "lib/fontconfig.properties.src",
    "lib/jfr/default.jfc",
    "lib/jfr/profile.jfc",
    "lib/jrt-fs.jar",
    "lib/jspawnhelper",
    "lib/jvm.cfg",
    "lib/libattach.dylib",
    "lib/libawt.dylib",
    "lib/libawt_lwawt.dylib",
    "lib/libdt_socket.dylib",
    "lib/libextnet.dylib",
    "lib/libfontmanager.dylib",
    "lib/libfreetype.dylib",
    "lib/libinstrument.dylib",
    "lib/libj2gss.dylib",
    "lib/libj2pcsc.dylib",
    "lib/libj2pkcs11.dylib",
    "lib/libjaas.dylib",
    "lib/libjava.dylib",
    "lib/libjavajpeg.dylib",
    "lib/libjawt.dylib",
    "lib/libjdwp.dylib",
    "lib/libjimage.dylib",
    "lib/libjli.dylib",
    "lib/libjsig.dylib",
    "lib/libjsound.dylib",
    "lib/liblcms.dylib",
    "lib/libmanagement.dylib",
    "lib/libmanagement_agent.dylib",
    "lib/libmanagement_ext.dylib",
    "lib/libmlib_image.dylib",
    "lib/libnet.dylib",
    "lib/libnio.dylib",
    "lib/libosx.dylib",
    "lib/libosxapp.dylib",
    "lib/libosxkrb5.dylib",
    "lib/libosxsecurity.dylib",
    "lib/libosxui.dylib",
    "lib/libprefs.dylib",
    "lib/librmi.dylib",
    "lib/libsaproc.dylib",
    "lib/libsplashscreen.dylib",
    "lib/libsunec.dylib",
    "lib/libunpack.dylib",
    "lib/libverify.dylib",
    "lib/libzip.dylib",
    "lib/modules",
    "lib/psfont.properties.ja",
    "lib/psfontj2d.properties",
    "lib/security/blacklisted.certs",
    "lib/security/cacerts",
    "lib/security/default.policy",
    "lib/security/public_suffix_list.dat",
    "lib/server/classes.jsa",
    "lib/server/libjsig.dylib",
    "lib/server/libjvm.dylib",
    "lib/src.zip",
    "lib/tzdb.dat",
  ],
  strip_components: 3,
)

java_compiler(
  name: "compiler",
  javac: "//lib/java/jdk13_macos:bin_javac",
  jar: "//lib/java/jdk13_macos:bin_jar",
  libs: "//lib/java/jdk13_macos:bin_javac_libs",
)

java_runtime(
  name: "runtime",
)
