# vim: ft=ruby

ruby_test(
  name: "LabelTest",
  srcs: ["label_test.rb"],
  deps: ["//src/main/ruby:wake"],
)

ruby_test(
  name: "TestingTest",
  srcs: ["testing_test.rb"],
  deps: ["//src/main/ruby:wake_testing"],
)

ruby_test(
  name: "WatchingTest",
  srcs: ["watching_test.rb"],
  deps: ["//src/main/ruby:wake"],
)

ruby_test(
  name: "WorkspaceTest",
  srcs: ["workspace_test.rb"],
  deps: ["//src/main/ruby:wake"],
)
