# vim: ft=ruby

ruby_test(
  name: "LabelTest",
  srcs: ["label_test.rb"],
  deps: [
    "//lib/rubygems/minitest:minitest",
    "//src/main/ruby/minitest:wake_plugin",
    "//src/main/ruby:wake",
  ],
)

ruby_test(
  name: "TestingTest",
  srcs: ["testing_test.rb"],
  deps: [
    "//lib/rubygems/minitest:minitest",
    "//src/main/ruby/minitest:wake_plugin",
    "//src/main/ruby:wake",
  ],
)

ruby_test(
  name: "WatchingTest",
  srcs: ["watching_test.rb"],
  deps: [
    "//lib/rubygems/minitest:minitest",
    "//src/main/ruby/minitest:wake_plugin",
    "//src/main/ruby:wake",
  ],
)

ruby_test(
  name: "WorkspaceTest",
  srcs: ["workspace_test.rb"],
  deps: [
    "//lib/rubygems/minitest:minitest",
    "//src/main/ruby/minitest:wake_plugin",
    "//src/main/ruby:wake",
  ],
)
