# vim: ft=ruby

http_file(
  name: "libffi",
  url: "https://download.jetbrains.com/kotlin/native/libffi-3.2.1-3-darwin-macos.tar.gz",
  sha256: nil,
  os: :macos,
)

http_file(
  name: "lldb",
  url: "https://download.jetbrains.com/kotlin/native/lldb-2-macos.tar.gz",
  sha256: nil,
  os: :macos,
)

http_file(
  name: "clang",
  url: "https://download.jetbrains.com/kotlin/native/clang-llvm-apple-8.0.0-darwin-macos.tar.gz",
  sha256: nil,
  os: :macos,
)
