# vim: ft=ruby

maven_jars(
  artifacts: [
    "org.apiguardian:apiguardian-api:1.1.0", # FIXME
    "org.jetbrains.intellij.deps:trove4j:1.0.20181211",
    "org.jetbrains.kotlin:kotlin-compiler:1.4.21",
    "org.jetbrains.kotlin:kotlin-reflect:1.4.21",
    "org.jetbrains.kotlin:kotlin-script-runtime:1.4.21",
    "org.jetbrains.kotlin:kotlin-serialization-unshaded:1.4.21",
    "org.jetbrains.kotlin:kotlin-stdlib:1.4.21",
    "org.jetbrains.kotlin:kotlin-test-junit5:1.4.21",
    "org.jetbrains.kotlin:kotlin-test:1.4.21",
    "org.jetbrains.kotlinx:kotlinx-serialization-core-jvm:1.0.1",
    "org.jetbrains.kotlinx:kotlinx-serialization-json-jvm:1.0.1",
    "org.jetbrains:annotations:13.0",
    "org.junit.jupiter:junit-jupiter-api:5.7.0",
    "org.junit.jupiter:junit-jupiter-engine:5.7.0",
    "org.junit.platform:junit-platform-commons:1.7.0", # FIXME
    "org.junit.platform:junit-platform-engine:1.7.0",
    "org.junit.platform:junit-platform-launcher:1.7.0",
    "org.opentest4j:opentest4j:1.2.0", # FIXME
  ],
)

maven_js_klibs(
  artifacts: [
    "org.jetbrains.kotlin:kotlin-stdlib-js:1.4.21@jar",
    "org.jetbrains.kotlin:kotlin-test-js:1.4.21@jar",
    "org.jetbrains.kotlinx:kotlinx-serialization-core-js:1.0.1@klib",
    "org.jetbrains.kotlinx:kotlinx-serialization-json-js:1.0.1@klib",
  ],
)

maven_native_klibs(
  artifacts: [
    "org.jetbrains.kotlinx:kotlinx-serialization-core-macosx64:1.0.1@klib",
    "org.jetbrains.kotlinx:kotlinx-serialization-json-macosx64:1.0.1@klib",
  ],
)
