java_library(
  name = "perquackey",
  srcs = glob(["*.java"]),
  deps = [
    "//src/main/java/org/matthewtodd/workflow",
    "@io_reactivex_rxjava2_rxjava//jar",
    "@org_reactivestreams_reactive_streams//jar",
  ],
  visibility = [
    "//src/main/java/org/matthewtodd/perquackey/console:__pkg__",
    "//src/test/java/org/matthewtodd/perquackey:__pkg__",
  ],
)
