java_library(
  name = "perquackey",
  srcs = glob(["*.java"]),
  deps = [
    "//src/main/java/org/matthewtodd/flow",
    "//src/main/java/org/matthewtodd/workflow",
  ],
  visibility = [
    "//src/main/java/org/matthewtodd/perquackey/console:__pkg__",
    "//src/test/java/org/matthewtodd/perquackey:__pkg__",
  ],
)
