java_library(
    name = "perquackey",
    srcs = glob(["*.java"]),
    resources = glob(["*.txt"]),
    visibility = [
        "//src/main/java/org/matthewtodd/perquackey/terminal:__pkg__",
        "//src/test/java/org/matthewtodd/perquackey:__pkg__",
    ],
    deps = [
        "//src/main/java/org/matthewtodd/flow",
        "//src/main/java/org/matthewtodd/workflow",
    ],
)
