java_library(
    name = "rebalance",
    srcs = glob(["*.java"]),
    resource_jars = [
        "//src/main/resources/org/matthewtodd/intellij/rebalance",
    ],
    deps = [
        "@intellij//:sdk",
    ],
)
