java_library(
    name = "rebalance",
    srcs = glob(["*.java"]),
    resource_strip_prefix = "src/main/java/org/matthewtodd/intellij/rebalance",
    resources = glob(["META-INF/*"]),
    deps = [
        "@intellij//:sdk",
    ],
)
