java_library(
    name = "rebalance",
    srcs = glob(["*.java"]),
    resource_jars = [
        "//src/main/resources/org/matthewtodd/intellij/rebalance",
    ],
    deps = [
        "@maven//:com_jetbrains_intellij_platform_core",
        "@maven//:com_jetbrains_intellij_platform_editor",
        "@maven//:com_jetbrains_intellij_platform_ide_impl",
        "@maven//:com_jetbrains_intellij_platform_util",
    ],
)
