# vim: ft=ruby

# https://kotlinlang.org/docs/reference/compiler-reference.html
http_archive(
  name: "kotlin",
  url: "https://github.com/JetBrains/kotlin/releases/download/v1.3.61/kotlin-compiler-1.3.61.zip",
  # sha256: "3901151ad5d94798a268d1771c6c0b7e305a608c2889fc98a674802500597b1c",
  strip_components: 1,
)
