# vim: ft=ruby

java_lib(
  name: "junit",
  srcs: ["WakeLauncher.java"],
  deps: [
    "//lib/maven/org_apiguardian/apiguardian_api:jar",
    "//lib/maven/org_junit_jupiter/junit_jupiter_engine:jar",
    "//lib/maven/org_junit_platform/junit_platform_commons:jar",
    "//lib/maven/org_junit_platform/junit_platform_engine:jar",
    "//lib/maven/org_junit_platform/junit_platform_launcher:jar",
  ],
)
