# vim: ft=ruby

# java_lib(
#   name: "junit",
#   srcs: ["WakeLauncher.java"],
#   deps: [
#     "//lib/maven/org_apiguardian/apiguardian-api",
#     "//lib/maven/org_junit_jupiter/junit-jupiter-engine",
#     "//lib/maven/org_junit_platform/junit-platform-commons",
#     "//lib/maven/org_junit_platform/junit-platform-engine",
#     "//lib/maven/org_junit_platform/junit-platform-launcher",
#   ],
# )
