# vim: ft=ruby

# java_lib(
#   name: "junit",
#   srcs: ["WakeLauncher.java"],
#   deps: [
#     "//lib/maven/org_apiguardian_apiguardian_api:apiguardian-api",
#     "//lib/maven/org_junit_jupiter_junit_jupiter_engine:junit-jupiter-engine",
#     "//lib/maven/org_junit_platform_junit_platform_commons:junit-platform-commons",
#     "//lib/maven/org_junit_platform_junit_platform_engine:junit-platform-engine",
#     "//lib/maven/org_junit_platform_junit_platform_launcher:junit-platform-launcher",
#     "//lib/maven/org_opentest4j_opentest4j:opentest4j",
#   ],
# )
