# vim: ft=ruby

kt_jvm_test(
  name: "WakeProjectOpenProcessorTest",
  srcs: ["WakeProjectOpenProcessorTest.kt"],
  deps: [
    "//lib/idea:sdk",
    "//src/main/kotlin/wake/idea:plugin",
    "//src/main/kotlin/wake/test:api_jvm",
    "//src/main/kotlin/wake/test:runtime_jvm",
  ],
  plugins: ["//src/main/kotlin/wake/test:plugin"],
)
