java_library(
    name = "terminal",
    testonly = True,
    srcs = glob(["*.java"]),
    visibility = [
        "//src/test/java/org/matthewtodd/perquackey/terminal:__pkg__",
    ],
    deps = [
        "//src/main/java/org/matthewtodd/terminal",
        "@maven//:org_assertj_assertj_core",
    ],
)
