java_library(
  name = "workflow",
  srcs = glob(["*.java"]),
  deps = [
    "//src/main/java/org/matthewtodd/workflow",
    "@org_assertj_assertj_core",
    "@org_reactivestreams_reactive_streams",
    "@io_reactivex_rxjava2_rxjava",
  ],
  testonly = True,
  visibility = [
    "//src/test/java/org/matthewtodd/perquackey:__pkg__"
  ],
)
