java_library(
  name = "workflow",
  srcs = glob(["*.java"]),
  deps = [
    "//src/main/java/org/matthewtodd/workflow",
    "//third_party:assertj",
    "//third_party:reactive_streams",
    "//third_party:rxjava2",
  ],
  visibility = [
    "//src/test/java/org/matthewtodd/perquackey:__pkg__"
  ],
)
