# vim: ft=ruby

# https://github.com/JetBrains/kotlin/releases/latest
http_file(
  name: "dist",
  url: "https://github.com/JetBrains/kotlin/releases/download/v1.4.10/kotlin-native-macos-1.4.10.tar.gz",
  sha256: nil,
)
