# vim: ft=ruby

http_file(
  name: "dist",
  url: "https://download.java.net/java/GA/jdk15/779bf45e88a44cbd9ea6621d33e33db1/36/GPL/openjdk-15_linux-x64_bin.tar.gz",
  sha256: "bb67cadee687d7b486583d03c9850342afea4593be4f436044d785fba9508fb7",
  os: :linux,
)

# tar tzf openjdk-15_linux-x64_bin.tar.gz | grep -v '/$' | grep -v '/legal/' | cut -d/ -f2- | sort | pbcopy
#
# bin/jaotc
# bin/jar
# bin/jarsigner
# bin/java
# bin/javac
# bin/javadoc
# bin/javap
# bin/jcmd
# bin/jconsole
# bin/jdb
# bin/jdeprscan
# bin/jdeps
# bin/jfr
# bin/jhsdb
# bin/jimage
# bin/jinfo
# bin/jlink
# bin/jmap
# bin/jmod
# bin/jpackage
# bin/jps
# bin/jrunscript
# bin/jshell
# bin/jstack
# bin/jstat
# bin/jstatd
# bin/keytool
# bin/rmid
# bin/rmiregistry
# bin/serialver
# conf/logging.properties
# conf/management/jmxremote.access
# conf/management/jmxremote.password.template
# conf/management/management.properties
# conf/net.properties
# conf/sdp/sdp.conf.template
# conf/security/java.policy
# conf/security/java.security
# conf/security/policy/README.txt
# conf/security/policy/limited/default_US_export.policy
# conf/security/policy/limited/default_local.policy
# conf/security/policy/limited/exempt_local.policy
# conf/security/policy/unlimited/default_US_export.policy
# conf/security/policy/unlimited/default_local.policy
# conf/sound.properties
# include/classfile_constants.h
# include/jawt.h
# include/jdwpTransport.h
# include/jni.h
# include/jvmti.h
# include/jvmticmlr.h
# include/linux/jawt_md.h
# include/linux/jni_md.h
# jmods/java.base.jmod
# jmods/java.compiler.jmod
# jmods/java.datatransfer.jmod
# jmods/java.desktop.jmod
# jmods/java.instrument.jmod
# jmods/java.logging.jmod
# jmods/java.management.jmod
# jmods/java.management.rmi.jmod
# jmods/java.naming.jmod
# jmods/java.net.http.jmod
# jmods/java.prefs.jmod
# jmods/java.rmi.jmod
# jmods/java.scripting.jmod
# jmods/java.se.jmod
# jmods/java.security.jgss.jmod
# jmods/java.security.sasl.jmod
# jmods/java.smartcardio.jmod
# jmods/java.sql.jmod
# jmods/java.sql.rowset.jmod
# jmods/java.transaction.xa.jmod
# jmods/java.xml.crypto.jmod
# jmods/java.xml.jmod
# jmods/jdk.accessibility.jmod
# jmods/jdk.aot.jmod
# jmods/jdk.attach.jmod
# jmods/jdk.charsets.jmod
# jmods/jdk.compiler.jmod
# jmods/jdk.crypto.cryptoki.jmod
# jmods/jdk.crypto.ec.jmod
# jmods/jdk.dynalink.jmod
# jmods/jdk.editpad.jmod
# jmods/jdk.hotspot.agent.jmod
# jmods/jdk.httpserver.jmod
# jmods/jdk.incubator.foreign.jmod
# jmods/jdk.incubator.jpackage.jmod
# jmods/jdk.internal.ed.jmod
# jmods/jdk.internal.jvmstat.jmod
# jmods/jdk.internal.le.jmod
# jmods/jdk.internal.opt.jmod
# jmods/jdk.internal.vm.ci.jmod
# jmods/jdk.internal.vm.compiler.jmod
# jmods/jdk.internal.vm.compiler.management.jmod
# jmods/jdk.jartool.jmod
# jmods/jdk.javadoc.jmod
# jmods/jdk.jcmd.jmod
# jmods/jdk.jconsole.jmod
# jmods/jdk.jdeps.jmod
# jmods/jdk.jdi.jmod
# jmods/jdk.jdwp.agent.jmod
# jmods/jdk.jfr.jmod
# jmods/jdk.jlink.jmod
# jmods/jdk.jshell.jmod
# jmods/jdk.jsobject.jmod
# jmods/jdk.jstatd.jmod
# jmods/jdk.localedata.jmod
# jmods/jdk.management.agent.jmod
# jmods/jdk.management.jfr.jmod
# jmods/jdk.management.jmod
# jmods/jdk.naming.dns.jmod
# jmods/jdk.naming.rmi.jmod
# jmods/jdk.net.jmod
# jmods/jdk.nio.mapmode.jmod
# jmods/jdk.sctp.jmod
# jmods/jdk.security.auth.jmod
# jmods/jdk.security.jgss.jmod
# jmods/jdk.unsupported.desktop.jmod
# jmods/jdk.unsupported.jmod
# jmods/jdk.xml.dom.jmod
# jmods/jdk.zipfs.jmod
# lib/classlist
# lib/ct.sym
# lib/jexec
# lib/jfr/default.jfc
# lib/jfr/profile.jfc
# lib/jrt-fs.jar
# lib/jspawnhelper
# lib/jvm.cfg
# lib/libattach.so
# lib/libawt.so
# lib/libawt_headless.so
# lib/libawt_xawt.so
# lib/libdt_socket.so
# lib/libextnet.so
# lib/libfontmanager.so
# lib/libinstrument.so
# lib/libj2gss.so
# lib/libj2pcsc.so
# lib/libj2pkcs11.so
# lib/libjaas.so
# lib/libjava.so
# lib/libjavajpeg.so
# lib/libjawt.so
# lib/libjdwp.so
# lib/libjimage.so
# lib/libjli.so
# lib/libjsig.so
# lib/libjsound.so
# lib/liblcms.so
# lib/libmanagement.so
# lib/libmanagement_agent.so
# lib/libmanagement_ext.so
# lib/libmlib_image.so
# lib/libnet.so
# lib/libnio.so
# lib/libprefs.so
# lib/librmi.so
# lib/libsaproc.so
# lib/libsctp.so
# lib/libsplashscreen.so
# lib/libsunec.so
# lib/libverify.so
# lib/libzip.so
# lib/modules
# lib/psfont.properties.ja
# lib/psfontj2d.properties
# lib/security/blacklisted.certs
# lib/security/cacerts
# lib/security/default.policy
# lib/security/public_suffix_list.dat
# lib/server/classes.jsa
# lib/server/classes_nocoops.jsa
# lib/server/libjsig.so
# lib/server/libjvm.so
# lib/src.zip
# lib/tzdb.dat
# release

extract(
  name: "bin_jar",
  archive: ":dist",
  format: :tar_gz,
  paths: ["bin/jar"],
  strip_components: 1,
  os: :linux,
)

extract(
  name: "bin_java",
  archive: ":dist",
  format: :tar_gz,
  paths: ["bin/java"],
  strip_components: 1,
  os: :linux,
)

extract(
  name: "lib",
  archive: ":dist",
  format: :tar_gz,
  paths: [
    "conf/logging.properties",
    "conf/management/jmxremote.access",
    "conf/management/jmxremote.password.template",
    "conf/management/management.properties",
    "conf/net.properties",
    "conf/sdp/sdp.conf.template",
    "conf/security/java.policy",
    "conf/security/java.security",
    "conf/security/policy/limited/default_US_export.policy",
    "conf/security/policy/limited/default_local.policy",
    "conf/security/policy/limited/exempt_local.policy",
    "conf/security/policy/unlimited/default_US_export.policy",
    "conf/security/policy/unlimited/default_local.policy",
    "conf/sound.properties",
    "lib/classlist",
    "lib/ct.sym",
    "lib/jexec",
    "lib/jfr/default.jfc",
    "lib/jfr/profile.jfc",
    "lib/jrt-fs.jar",
    "lib/jspawnhelper",
    "lib/jvm.cfg",
    "lib/libattach.so",
    "lib/libawt.so",
    "lib/libawt_headless.so",
    "lib/libawt_xawt.so",
    "lib/libdt_socket.so",
    "lib/libextnet.so",
    "lib/libfontmanager.so",
    "lib/libinstrument.so",
    "lib/libj2gss.so",
    "lib/libj2pcsc.so",
    "lib/libj2pkcs11.so",
    "lib/libjaas.so",
    "lib/libjava.so",
    "lib/libjavajpeg.so",
    "lib/libjawt.so",
    "lib/libjdwp.so",
    "lib/libjimage.so",
    "lib/libjli.so",
    "lib/libjsig.so",
    "lib/libjsound.so",
    "lib/liblcms.so",
    "lib/libmanagement.so",
    "lib/libmanagement_agent.so",
    "lib/libmanagement_ext.so",
    "lib/libmlib_image.so",
    "lib/libnet.so",
    "lib/libnio.so",
    "lib/libprefs.so",
    "lib/librmi.so",
    "lib/libsaproc.so",
    "lib/libsctp.so",
    "lib/libsplashscreen.so",
    "lib/libsunec.so",
    "lib/libverify.so",
    "lib/libzip.so",
    "lib/modules",
    "lib/psfont.properties.ja",
    "lib/psfontj2d.properties",
    "lib/security/blacklisted.certs",
    "lib/security/cacerts",
    "lib/security/default.policy",
    "lib/security/public_suffix_list.dat",
    "lib/server/classes.jsa",
    "lib/server/libjsig.so",
    "lib/server/libjvm.so",
    "lib/src.zip",
    "lib/tzdb.dat",
  ],
  strip_components: 1,
  os: :linux,
)

java_archiver(
  name: "archiver",
  jar: ":bin_jar",
  libs: ":lib",
  os: :linux,
)

java_runtime(
  name: "runtime",
  java: ":bin_java",
  libs: ":lib",
  os: :linux,
)
