java_library(
    name = "bazel",
    resource_strip_prefix = "src/main/resources/org/matthewtodd/intellij/bazel",
    resources = glob(["META-INF/*.xml"]),
    visibility = ["//src/main/java/org/matthewtodd/intellij/bazel:__pkg__"],
)
