java_library(
    name = "rebalance",
    resource_strip_prefix = "src/main/resources/org/matthewtodd/intellij/rebalance",
    resources = glob(["META-INF/*.xml"]),
    visibility = ["//src/main/java/org/matthewtodd/intellij/rebalance:__pkg__"],
)
