# vim: ft=ruby

kt_js_test(
  name: "test-result-test",
  srcs: ["TestResultTest.kt"],
  deps: [
    "//lib/maven/org_jetbrains_kotlinx/kotlinx_serialization_core_js:jar",
    "//src/main/kotlin/wake/test:js",
  ],
)

kt_jvm_test(
  name: "TestResultTestJvm",
  srcs: ["TestResultTest.kt"],
  deps: [
    "//lib/maven/org_jetbrains_kotlinx/kotlinx_serialization_core_jvm:jar",
    "//src/main/kotlin/wake/test:junit",
  ],
)
