java_library(
  name = "flow",
  srcs = glob(["*.java"]),
  deps = [
    "//third_party:reactive_streams",
    "//third_party:rxjava2",
    "//third_party:rxjava2_extensions",
  ],
  exports = [
    "//third_party:reactive_streams",
  ],
  visibility = ["//visibility:public"],
)
