java_library(
    name = "flow",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    exports = [
        "@maven//:org_reactivestreams_reactive_streams",
    ],
    deps = [
        "@maven//:com_github_akarnokd_rxjava2_extensions",
        "@maven//:io_reactivex_rxjava2_rxjava",
        "@maven//:org_reactivestreams_reactive_streams",
    ],
)
