# vim: ft=ruby

ruby_test(
  name: "ConcurrentTest",
  srcs: ["concurrent_test.rb"],
  deps: ["//src/main/ruby:concurrent"],
)

ruby_test(
  name: "WakeTest",
  srcs: ["wake_test.rb"],
  deps: ["//src/main/ruby:wake"],
)
